

# =============================================================================
# NORMAL / POSITIVE WORDS  (plain list – no severity needed)
# =============================================================================
NORMAL_WORDS = [

    #  Nepali: Greetings & Salutations 
    "नमस्ते", "नमस्कार", "प्रणाम", "जय नेपाल", "सुस्वागतम्", "स्वागत",
    "शुभ प्रभात", "शुभ दिउँसो", "शुभ सन्ध्या", "शुभ रात्रि", "शुभकामना",
    "शुभ यात्रा", "शुभ विवाह", "शुभ जन्मदिन", "शुभ दशैँ", "शुभ तिहार",
    "शुभ नयाँ वर्ष", "शुभ होली", "शुभ इद", "शुभ क्रिसमस",
    "हार्दिक स्वागत", "हार्दिक शुभकामना", "हार्दिक बधाई",
    "फेरी भेटौला", "फेरी आउनुस्", "बिदा", "अलविदा",

    #  Nepali: Gratitude & Politeness 
    "धन्यवाद", "धेरै धन्यवाद", "बहुत धन्यवाद", "आभारी छु", "कृतज्ञ",
    "कृपया", "हजुर", "ठिक छ", "माफ गर्नुहोस्", "क्षमा गर्नुहोस्",
    "दया गर्नुहोस्", "मेहेरबानी", "सहयोगका लागि धन्यवाद",
    "सहयोग गर्नुभएकोमा धन्यवाद", "तपाईंको कृपा",

    #  Nepali: Compliments & Praise 
    "राम्रो", "राम्री", "सुन्दर", "सुन्दरी", "आकर्षक", "मनोरम",
    "मिठो", "मीठो", "मजेदार", "रोमाञ्चक", "अद्भुत", "अद्वितीय",
    "उत्कृष्ट", "उत्तम", "उत्साहजनक", "प्रशंसनीय", "प्रभावशाली",
    "सफा", "स्वच्छ", "शुद्ध", "ताजा", "नयाँ", "अनौठो",
    "शानदार", "भव्य", "महान्", "महत्त्वपूर्ण", "विशेष",
    "विशेष गरी", "असाधारण", "अपूर्व", "अनुपम", "बेजोड",
    "चाखलाग्दो", "रोचक", "रमाइलो", "आनन्ददायी", "खुशीको",
    "बहादुर", "साहसी", "शक्तिशाली", "दृढ", "मेहनती",
    "लगनशील", "परिश्रमी", "ईमानदार", "सत्यनिष्ठ", "विश्वसनीय",
    "भरपर्दो", "विद्वान्", "बुद्धिमान्", "चतुर", "होशियार",
    "प्रतिभाशाली", "कुशल", "दक्ष", "निपुण", "सिपालु",
    "दयालु", "करुणामय", "माया गर्ने", "प्रेमी", "स्नेही",
    "सहयोगी", "मिलनसार", "मैत्रीपूर्ण", "हँसिलो", "खुशी",
    "सौम्य", "शान्त", "धैर्यशील", "सहनशील", "सरल",
    "विनम्र", "नम्र", "सभ्य", "शिष्ट", "भद्र",
    "प्रेरणादायक", "उत्प्रेरक", "उदाहरणीय", "आदर्श", "नमूना",
    "स्वस्थ", "निरोगी", "तन्दुरुस्त", "सक्रिय", "चुस्त",
    "फुर्तिलो", "जोशिलो", "उत्साही", "जाँगरिलो", "अग्रगामी",
    "सफल", "विजयी", "समृद्ध", "सम्पन्न", "खुशहाल",
    "प्रगतिशील", "विकासशील", "उन्नतिशील", "उत्थानशील", "अगाडि बढ्ने",
    "ज्ञानी", "सुशिक्षित", "पढेलेखेको", "सिकेको", "अनुभवी",
    "परिपक्व", "सुलझिएको", "सम्झदार", "बुझक्कड", "समझदार",
    "न्यायप्रिय", "इन्साफपसन्द", "धर्मनिष्ठ", "नैतिक", "ईमानदार",
    "इमानदार", "खरो", "साहसी", "हिम्मती", "निडर",
    "आत्मविश्वासी", "दृढसंकल्पी", "लक्ष्यनिष्ठ", "समर्पित", "कर्तव्यनिष्ठ",
    "उदार", "दानशील", "परोपकारी", "दयावान्", "सेवाभावी",
    "सेवक", "सहयोगी", "सहकर्मी", "साथी", "मित्र",
    "प्रिय", "प्यारो", "मनपर्ने", "मनमोहक", "आनन्ददायी",

    # Nepali: Emotions & Feelings (Positive)     "खुशी", "प्रसन्न", "हर्षित", "आनन्दित", "उल्लसित",
    "सन्तुष्ट", "सन्तोषजनक", "तृप्त", "तृप्तिदायक", "शान्त",
    "शान्तिपूर्ण", "स्थिर", "निर्भय", "आत्मसन्तुष्ट", "मनमग्न",
    "प्रेम", "माया", "ममता", "स्नेह", "अनुराग",
    "वात्सल्य", "करुणा", "दया", "सहानुभूति", "समानुभूति",
    "सद्भाव", "मित्रता", "भाईचारा", "सहयोग", "एकता",
    "ऐक्य", "समन्वय", "सहकार्य", "मेलमिलाप", "सुलह",
    "उमङ्ग", "उत्साह", "जोश", "जाँगर", "फूर्ति",
    "साहस", "हिम्मत", "बल", "शक्ति", "सामर्थ्य",
    "विश्वास", "भरोसा", "आस्था", "श्रद्धा", "भक्ति",
    "सम्मान", "आदर", "प्रतिष्ठा", "मान", "इज्जत",
    "गर्व", "अभिमान", "स्वाभिमान", "आत्मसम्मान", "इज्जत",
    "उपलब्धि", "सफलता", "जित", "विजय", "कामयाबी",
    "कीर्ति", "यश", "नाम", "ख्याति", "प्रसिद्धि",

    # Nepali: Nature & Beauty 
    "हिमाल", "पहाड", "नदी", "झरना", "जंगल",
    "बगैचा", "फूल", "हरियाली", "प्रकृति", "वातावरण",
    "आकाश", "सूर्य", "चन्द्रमा", "तारा", "इन्द्रेणी",
    "बिहानी", "साँझ", "रात", "दिन", "मौसम",
    "वसन्त", "हिउँ", "वर्षा", "शिशिर", "ग्रीष्म",
    "सुनौलो", "रातो", "निलो", "हरियो", "पहेंलो",
    "सेतो", "सुन्दर रंग", "रंगीन", "बहुरंगी", "प्राकृतिक",

    #  Nepali: Food & Taste 
    "स्वादिष्ट", "मिठो खाना", "सुस्वादु", "चिल्लो", "मसालेदार",
    "ताजा खाना", "पौष्टिक", "स्वास्थ्यकर", "सुपाच्य", "रुचिकर",
    "भोज", "खाना", "भात", "दाल", "तरकारी",
    "फलफूल", "पानी", "जुस", "चिया", "कफी",
    "मिष्ठान", "मिठाई", "हलवा", "खिर", "सेल",

    #  Nepali: Family & Relationships 
    "आमा", "बुवा", "दिदी", "दाइ", "बहिनी",
    "भाइ", "साथी", "मित्र", "प्रेमी", "प्रेमिका",
    "श्रीमान्", "श्रीमती", "परिवार", "घर", "घरपरिवार",
    "समाज", "समुदाय", "छिमेकी", "गाउँ", "टोल",
    "आफन्त", "नातेदार", "हजुरआमा", "हजुरबुवा", "काका",
    "काकी", "फुपू", "मामा", "माइजू", "साथीभाइ",

    #  Nepali: Education & Knowledge 
    "शिक्षा", "विद्या", "ज्ञान", "सीप", "विवेक",
    "बुद्धि", "चेतना", "जागरण", "सचेत", "जागरुक",
    "पढाइ", "लेखाइ", "अनुसन्धान", "खोज", "अध्ययन",
    "विद्यालय", "विश्वविद्यालय", "कलेज", "पाठशाला", "गुरु",
    "शिक्षक", "विद्यार्थी", "छात्र", "छात्रा", "शिक्षार्थी",
    "किताब", "पुस्तक", "पत्रिका", "समाचार", "जानकारी",
    "सूचना", "तथ्य", "प्रमाण", "तर्क", "विश्लेषण",

    #  Nepali: Work & Achievement   
    "काम", "मेहनत", "परिश्रम", "लगन", "समर्पण",
    "उत्पादन", "सिर्जना", "निर्माण", "विकास", "उन्नति",
    "प्रगति", "सुधार", "परिवर्तन", "नवाचार", "आविष्कार",
    "उद्योग", "व्यापार", "कम्पनी", "संस्था", "सेवा",
    "कार्यालय", "कर्मचारी", "श्रमिक", "किसान", "व्यापारी",

    #  Nepali: Culture & Values 
    "संस्कृति", "परम्परा", "रीतिरिवाज", "चाडपर्व", "उत्सव",
    "धर्म", "आस्था", "विश्वास", "नैतिकता", "मूल्य",
    "सिद्धान्त", "आदर्श", "नमूना", "मानवता", "मानवीयता",
    "समानता", "न्याय", "स्वतन्त्रता", "अधिकार", "कर्तव्य",
    "देशभक्ति", "राष्ट्रप्रेम", "देशप्रेम", "गौरव", "शान",
    "शान्ति", "सद्भाव", "एकता", "अखण्डता", "सम्प्रभुता",

    #  Nepali: Encouragement & Motivation 
    "हार नमान्नु", "अगाडि बढ", "जारी राख", "कोसिस गर",
    "सक्छौ", "सक्नुहुन्छ", "गर्न सकिन्छ", "विश्वास राख",
    "मेहनत गर", "सफल हुन्छौ", "जित्छौ", "जित्नुहुन्छ",
    "प्रयास गर", "थकान नमान्नु", "आत्मविश्वास राख",
    "तिमीले गर्न सक्छौ", "तपाईंले गर्न सक्नुहुन्छ",
    "राम्रो गर्यौ", "धेरै राम्रो", "सबाश", "शाबास",
    "बधाई छ", "बधाई दिन्छु", "अभिनन्दन", "मुबारक",
    "तहसिल", "ईनाम", "पुरस्कार", "सम्मान", "मेडल",

    # English: Greetings & Salutations 
    "hello", "hi", "hey", "howdy", "greetings",
    "good morning", "good afternoon", "good evening", "good night",
    "welcome", "namaste", "salutations", "cheers", "aloha",
    "bonjour", "ciao", "hola", "shalom", "salaam",
    "see you", "take care", "farewell", "goodbye", "bye",
    "catch you later", "talk soon", "until next time",

    # English: Gratitude & Politeness 
    "thank you", "thanks", "many thanks", "much appreciated",
    "grateful", "thankful", "appreciate", "gratitude",
    "please", "kindly", "excuse me", "pardon", "sorry",
    "my apologies", "forgive me", "no worries", "of course",
    "absolutely", "certainly", "definitely", "sure", "gladly",
    "you're welcome", "anytime", "my pleasure", "happy to help",

    # English: Compliments 
    "good", "great", "nice", "wonderful", "fantastic",
    "excellent", "outstanding", "superb", "terrific", "splendid",
    "magnificent", "marvelous", "spectacular", "brilliant", "exceptional",
    "extraordinary", "phenomenal", "remarkable", "impressive", "stunning",
    "beautiful", "gorgeous", "lovely", "pretty", "elegant",
    "charming", "graceful", "delightful", "adorable", "cute",
    "amazing", "awesome", "incredible", "unbelievable", "wow",
    "perfect", "flawless", "immaculate", "pristine", "ideal",
    "super", "cool", "epic", "legendary", "iconic",
    "rad", "stellar", "ace", "top-notch", "first-rate",
    "quality", "premium", "superior", "world-class", "best",
    "exquisite", "divine", "heavenly", "glorious", "radiant",
    "vibrant", "vivid", "lively", "dynamic", "energetic",
    "refreshing", "invigorating", "uplifting", "inspiring", "motivating",

    # English: Character & Personality 
    "kind", "gentle", "caring", "loving", "compassionate",
    "empathetic", "understanding", "supportive", "nurturing", "warm",
    "friendly", "sociable", "outgoing", "welcoming", "hospitable",
    "generous", "giving", "charitable", "philanthropic", "benevolent",
    "humble", "modest", "polite", "courteous", "respectful",
    "honest", "truthful", "sincere", "genuine", "authentic",
    "trustworthy", "reliable", "dependable", "loyal", "faithful",
    "brave", "courageous", "bold", "fearless", "daring",
    "confident", "determined", "resilient", "persistent", "tenacious",
    "intelligent", "smart", "clever", "wise", "knowledgeable",
    "creative", "innovative", "inventive", "imaginative", "artistic",
    "talented", "gifted", "skilled", "proficient", "expert",
    "hardworking", "diligent", "industrious", "dedicated", "committed",
    "patient", "calm", "serene", "peaceful", "composed",
    "cheerful", "happy", "joyful", "bubbly", "optimistic",
    "positive", "upbeat", "enthusiastic", "passionate", "motivated",
    "ambitious", "goal-oriented", "driven", "focused", "disciplined",
    "responsible", "accountable", "conscientious", "thorough", "meticulous",
    "adaptable", "flexible", "open-minded", "broad-minded", "tolerant",
    "fair", "just", "ethical", "moral", "principled",
    "noble", "virtuous", "righteous", "upstanding", "honorable",
    "charismatic", "magnetic", "captivating", "enchanting", "mesmerizing",
    "witty", "humorous", "funny", "playful", "jovial",

    # English: Emotions & Feelings 
    "happy", "elated", "overjoyed", "ecstatic", "blissful",
    "content", "satisfied", "fulfilled", "pleased", "glad",
    "excited", "thrilled", "euphoric", "exhilarated", "jubilant",
    "proud", "accomplished", "triumphant", "victorious", "successful",
    "grateful", "blessed", "fortunate", "lucky", "privileged",
    "hopeful", "optimistic", "encouraged", "uplifted", "inspired",
    "loved", "cherished", "adored", "treasured", "valued",
    "calm", "relaxed", "at peace", "tranquil", "serene",
    "joy", "happiness", "delight", "pleasure", "bliss",
    "love", "affection", "warmth", "tenderness", "fondness",
    "gratitude", "appreciation", "admiration", "respect", "esteem",
    "hope", "faith", "belief", "trust", "confidence",
    "pride", "honor", "dignity", "glory", "triumph",
    "enthusiasm", "passion", "zeal", "fervor", "ardor",

    #  English: Positive Actions 
    "help", "assist", "support", "aid", "serve",
    "create", "build", "make", "construct", "develop",
    "improve", "enhance", "upgrade", "refine", "perfect",
    "learn", "study", "grow", "progress", "advance",
    "achieve", "accomplish", "succeed", "excel", "flourish",
    "share", "give", "donate", "contribute", "volunteer",
    "protect", "defend", "guard", "preserve", "conserve",
    "heal", "restore", "recover", "revive", "renew",
    "celebrate", "honor", "cherish", "appreciate", "enjoy",
    "inspire", "motivate", "encourage", "empower", "uplift",
    "collaborate", "cooperate", "partner", "unite", "join",
    "lead", "guide", "mentor", "teach", "educate",
    "innovate", "pioneer", "transform", "revolutionize", "change",
    "nurture", "care", "tend", "cultivate", "foster",
    "smile", "laugh", "sing", "dance", "play",

    #English: Social & Community 
    "community", "family", "friendship", "brotherhood", "sisterhood",
    "unity", "solidarity", "togetherness", "harmony", "cooperation",
    "peace", "love", "kindness", "compassion", "empathy",
    "diversity", "inclusion", "equality", "fairness", "justice",
    "freedom", "liberty", "democracy", "rights", "dignity",
    "culture", "heritage", "tradition", "celebration", "festival",
    "education", "knowledge", "wisdom", "enlightenment", "awareness",
    "progress", "development", "growth", "prosperity", "abundance",
    "health", "wellness", "fitness", "vitality", "energy",
    "nature", "environment", "ecology", "sustainability", "conservation",

    # English: Encouragement
    "well done", "good job", "keep it up", "great work",
    "you can do it", "believe in yourself", "stay strong",
    "never give up", "you got this", "press on",
    "outstanding effort", "keep going", "push through", "stay focused",
    "bravo", "kudos", "congrats", "congratulations", "hats off",
    "well played", "nicely done", "top job", "way to go",
    "that's the spirit", "you're doing great", "proud of you",
    "you're amazing", "you're awesome", "you're incredible",
    "you're talented", "you're gifted", "you're a star",
    "respect", "admiration", "applause", "recognition", "award",
    "champion", "winner", "hero", "legend", "icon",
    "role model", "inspiration", "example", "leader", "pioneer",

    #  English: Adjectives (Positive) 
    "abundant", "accessible", "accomplished", "accurate", "active",
    "admirable", "adorable", "advanced", "affectionate", "agile",
    "altruistic", "amiable", "ample", "angelic", "animated",
    "appealing", "appreciative", "apt", "ardent", "artful",
    "aspiring", "astounding", "attentive", "august", "auspicious",
    "authentic", "avid", "balanced", "beatific", "beloved",
    "beneficent", "bountiful", "bright", "capable", "captivating",
    "celebrated", "cheerful", "clear", "coherent", "colorful",
    "competent", "complete", "comprehensive", "conscientious", "constructive",
    "courageous", "crisp", "cultivated", "dazzling", "dedicated",
    "deliberate", "desirable", "devoted", "dignified", "diplomatic",
    "earnest", "effective", "efficient", "eloquent", "empowered",
    "enchanting", "endearing", "enlightened", "enriching", "essential",
    "esteemed", "evocative", "exemplary", "expressive", "exuberant",
    "fabulous", "fair-minded", "familiar", "favorable", "fervent",
    "fitting", "flourishing", "focused", "forthcoming", "frank",
    "free", "fresh", "full", "functional", "genuine",
    "giving", "glowing", "good-natured", "gracious", "grand",
    "grateful", "great", "grounded", "growing", "guiding",
    "handsome", "harmonious", "heartfelt", "helpful", "heroic",
    "holistic", "hopeful", "ideal", "illuminating", "imaginative",
    "impactful", "inclusive", "ingenious", "insightful", "integral",
    "jubilant", "judicious", "keen", "kindhearted", "knowledgeable",
    "laudable", "learned", "level-headed", "light", "logical",
    "lovable", "loving", "luminous", "masterful", "mature",
    "meaningful", "mindful", "moral", "natural", "neat",
    "nurturing", "objective", "open", "optimistic", "orderly",
    "original", "passionate", "patient", "perceptive", "pioneering",
    "pleasant", "poised", "polished", "positive", "powerful",
    "practical", "precise", "proactive", "productive", "progressive",
    "proper", "prosperous", "purposeful", "quick-witted", "rational",
    "receptive", "refined", "refreshed", "regal", "reliable",
    "renewed", "resilient", "resourceful", "respectful", "responsive",
    "robust", "safe", "sensible", "sensitive", "serene",
    "sharp", "sincere", "skillful", "smart", "spirited",
    "spontaneous", "stable", "steadfast", "strong", "structured",
    "supportive", "thoughtful", "timely", "tireless", "tolerant",
    "transparent", "triumphant", "trustworthy", "truthful", "understanding",
    "unique", "united", "upright", "useful", "valued",
    "versatile", "vibrant", "vigilant", "visionary", "vital",
    "vivid", "warm-hearted", "wholesome", "willing", "wise",
    "wonderful", "worthy", "youthful", "zealous", "zen",

    #  English: Nature & Environment 
    "sunshine", "rainbow", "blossom", "meadow", "garden",
    "forest", "ocean", "river", "mountain", "valley",
    "breeze", "fresh air", "clear sky", "starry night", "moonlight",
    "sunrise", "sunset", "dawn", "twilight", "horizon",
    "green", "blue", "golden", "silver", "crystal",
    "bloom", "flourish", "thrive", "grow", "renew",
    "spring", "summer", "autumn", "winter", "season",
    "bird song", "butterfly", "honeybee", "dewdrop", "serenity",

    #  English: Food & Pleasure 
    "delicious", "tasty", "scrumptious", "yummy", "flavorful",
    "appetizing", "savory", "sweet", "fresh", "nutritious",
    "wholesome", "organic", "natural", "healthy", "nourishing",
    "feast", "banquet", "celebration", "party", "gathering",
    "music", "art", "dance", "poetry", "literature",
    "sport", "game", "hobby", "recreation", "leisure",
    "travel", "adventure", "exploration", "discovery", "journey",
    "vacation", "holiday", "rest", "relaxation", "peace",

    # English: Positive Phrases 
    "all the best", "best wishes", "good luck", "fingers crossed",
    "you rock", "you shine", "you matter", "you are valued",
    "stay blessed", "stay safe", "take care", "be well",
    "much love", "with love", "sending love", "warm regards",
    "best regards", "kind regards", "warm wishes", "heartfelt thanks",
    "great to see you", "glad to meet you", "nice to know you",
    "you are a blessing", "you are special", "one of a kind",
    "made my day", "brightened my day", "sunshine of my life",
    "heart of gold", "salt of the earth", "beacon of hope",
    "pillar of strength", "tower of strength", "ray of light",

    #  English: Additional positive adjectives 
    "affable", "agreeable", "alert", "alive", "alluring",
    "amicable", "appreciable", "approachable", "arduous", "artistic",
    "assertive", "astute", "attractive", "audacious", "authentic",
    "award-winning", "balanced", "beaming", "beatific", "becoming",
    "befitting", "believable", "benefiting", "benign", "blameless",
    "blossoming", "bounteous", "brave-hearted", "buoyant", "capable",
    "centered", "charitable", "clean", "clear-headed", "collected",
    "committed", "communicative", "compassionate", "competent", "considerate",
    "constructive", "content", "contributing", "cordial", "courageous",
    "creative", "crisp", "cultivated", "dashing", "dauntless",
    "dazzling", "dedicated", "decisive", "decent", "deliberate",
    "dependable", "deserving", "determined", "devout", "dignified",
    "diligent", "diplomatic", "distinguished", "driven", "dutiful",
    "earnest", "easygoing", "effective", "efficient", "elegant",
    "empowered", "enchanting", "encouraging", "energized", "engaging",
    "enlightened", "enriched", "enterprising", "enthusiastic", "essential",
    "ethical", "evolved", "exceptional", "expressive", "extraordinary",
    "fabulous", "fair", "faithful", "fearless", "fervent",
    "focused", "forthright", "friendly", "genuine", "gifted",
    "giving", "graceful", "great-hearted", "grounded", "happy-go-lucky",
    "hardworking", "harmonious", "heartfelt", "helpful", "high-spirited",
    "honest", "honorable", "hopeful", "humble", "illuminated",
    "imaginative", "impactful", "inclusive", "independent", "industrious",
    "innovative", "insightful", "inspirational", "integrous", "intellectual",
    "judicious", "kindhearted", "knowledgeable", "laudable", "likeable",
    "loving", "luminous", "masterful", "meaningful", "meticulous",
    "mindful", "motivated", "natural", "nice", "noble",
    "nurturing", "open-hearted", "optimistic", "outstanding", "passionate",
    "patient", "peaceful", "persistent", "philanthropic", "polished",
    "positive", "powerful", "principled", "proactive", "productive",
    "progressive", "purposeful", "radiant", "reliable", "resilient",
    "resourceful", "respectful", "responsible", "robust", "sincere",
    "skilled", "smart", "spirited", "stable", "steadfast",
    "strong-willed", "supportive", "talented", "thoughtful", "tireless",
    "tolerant", "transparent", "trustworthy", "understanding", "unified",
    "unique", "uplifting", "useful", "vibrant", "vigilant",
    "visionary", "warm", "wholesome", "wise", "worthy",

    # English: Motivational / Quote-style words 
    
    "ascend", "evolve", "transform", "reinvent", "reclaim",
    "empower", "liberate", "ignite", "spark", "kindle",
    "cultivate", "nurture", "harness", "leverage", "maximize",
    "optimize", "innovate", "pioneer", "lead", "inspire",
    "mentor", "guide", "influence", "impact", "change",
    "champion", "advocate", "defend", "protect", "serve",
    "commit", "dedicate", "sacrifice", "endure", "persist",
    "trust", "believe", "hope", "dream", "aspire",
    "pursue", "seek", "discover", "explore", "venture",

    #  More English positive nouns 
    "achievement", "advancement", "adventure", "affection", "alliance",
    "ambition", "appreciation", "aspiration", "beauty", "benefit",
    "blessing", "bond", "breakthrough", "brilliance", "calm",
    "capability", "care", "celebration", "charity", "cheerfulness",
    "clarity", "collaboration", "comfort", "commitment", "compassion",
    "competence", "confidence", "contentment", "cooperation", "courage",
    "creativity", "curiosity", "dedication", "delight", "devotion",
    "dignity", "discipline", "discovery", "diversity", "dream",
    "effectiveness", "empathy", "encouragement", "endurance", "energy",
    "enlightenment", "excellence", "exploration", "faith", "familiarity",
    "family", "flexibility", "focus", "forgiveness", "freedom",
    "friendship", "fulfillment", "generosity", "gentleness", "grace",
    "gratitude", "growth", "guidance", "harmony", "health",
    "heart", "heritage", "honor", "hope", "humility",
    "imagination", "impact", "improvement", "innovation", "inspiration",
    "integrity", "intelligence", "joy", "justice", "kindness",
    "knowledge", "leadership", "legacy", "light", "love",
    "loyalty", "mastery", "meaning", "mindfulness", "motivation",
    "nobility", "openness", "opportunity", "optimism", "order",
    "passion", "patience", "peace", "perseverance", "potential",
    "power", "pride", "progress", "prosperity", "purpose",
    "quality", "resilience", "respect", "responsibility", "safety",
    "service", "sincerity", "skill", "smile", "spirit",
    "strength", "success", "support", "talent", "thankfulness",
    "tolerance", "transformation", "trust", "truth", "understanding",
    "unity", "value", "victory", "virtue", "vision",
    "warmth", "wisdom", "wonder", "worth", "zeal",

    #  Nepali: Additional positive words 
    "सहयोग", "सहकार्य", "सहभागिता", "सांझेदारी", "मिलजुल",
    "आपसी", "परस्पर", "सामूहिक", "संयुक्त", "समन्वित",
    "विकास", "समृद्धि", "खुशहाली", "सम्पन्नता", "सफलता",
    "उत्तिर्ण", "उत्कृष्ट", "अग्रणी", "श्रेष्ठ", "पहिलो",
    "ऐतिहासिक", "स्मरणीय", "अविस्मरणीय", "अमर", "अनन्त",
    "सकारात्मक", "सृजनशील", "रचनात्मक", "कल्पनाशील", "दूरदर्शी",
    "सार्थक", "उद्देश्यपूर्ण", "फलदायी", "लाभदायक", "हितकारी",
    "लोकप्रिय", "मनपर्दो", "चाहिने", "आवश्यक", "उपयोगी",
    "व्यावहारिक", "व्यावसायिक", "पेशेवर", "दक्ष", "कुशल",
    "सिपालु", "हुनार", "गुण", "विशेषता", "क्षमता",
    "प्रतिभा", "कला", "हस्तकला", "सीप", "ज्ञान",
    "अनुभव", "दक्षता", "योग्यता", "कार्यकुशलता", "प्रभावकारिता",
    "सकारात्मक सोच", "राम्रो विचार", "असल मन", "उदार हृदय",
    "दयालु मन", "करुणामय हृदय", "प्रेमपूर्ण", "स्नेहपूर्ण",
    "आत्मीय", "मनको मान्छे", "असल साथी", "सच्चो मित्र",
    "विश्वासपात्र", "भरोसाको मान्छे", "इमानदार", "सत्यवादी",
    "न्यायपरायण", "धर्मपरायण", "सेवापरायण", "देशभक्त", "राष्ट्रसेवक",
    "समाजसेवी", "परोपकारी", "दानी", "उदारमना", "महानुभाव",

    # Nepali: Common Everyday Words (frequently used, must be recognized as safe)
    "ठिक", "ठीक", "ठीक छ", "हुन्छ", "हुन्थ्यो", "हुनेछ",

    "छ", "छन्", "छैन", "भयो", "भएन", "भइरहेको",
    "गर्नुस्", "गरौं", "गरिरहेको", "गर्दैछु", "गर्दैन",
    "आउनुस्", "आउँदैछु", "आउँछ", "जानुस्", "जाँदैछु",
    "बस", "बसौं", "बसेको", "खाऊ", "खाऔं", "खाएको",
    "के छ", "के छ?", "कसरी", "किन", "कहाँ", "कहिले",
    "यो", "त्यो", "यहाँ", "त्यहाँ", "अहिले", "पछि",
    "राम्रो छ", "ठिक्कै छ", "हो", "होइन", "हैन",
    "मान्छे", "केटो", "केटी", "बच्चा", "युवा", "बुढो", "बुढी",
    "यार", "दोस्त", "भाइ", "दाइ", "दिदी", "बहिनी",
    "के हो", "के भन्नुभयो", "बुझें", "बुझिनँ", "ओके", "ok", "okay",
    "हाँस्नु", "हाँस्छु", "रुनु", "रुँदैछु", "हाँसो", "रुवाइ",
    "मस्त", "मस्ती", "जाडो", "गर्मी", "भोक", "तिर्खा",
    "पैसा", "रुपैयाँ", "पसल", "बजार", "सडक", "घर",
    "मोबाइल", "फोन", "इन्टरनेट", "कम्प्युटर", "ल्यापटप",
    "बिरामी", "स्वस्थ", "दुख्छ", "पीडा", "आराम",
    "सुत्नु", "उठ्नु", "नुहाउनु", "खाना पकाउनु",
    "भोलि", "हिजो", "आज", "साँझ", "बिहान", "दिउँसो",
    "खेल", "खेल्नु", "दौड", "नाच", "गीत", "संगीत",
    "टोली", "समूह", "कक्षा", "परीक्षा", "नतिजा",
    "समय", "घडी", "मिनेट", "घण्टा", "दिन", "हप्ता",
    "महिना", "वर्ष", "साल", "युग",

    # Nepali Colloquial / Slang (safe, common in youth conversation)
    "यार", "भाइ", "भाई", "दाइ", "दाई", "सर", "म्याम",
    "छ नि", "हो नि", "हैन र", "हैन नि", "के गर्ने",
    "एक्दम", "एकदम", "धेरै", "अलि अलि", "थोरै",
    "माथि", "तल", "अगाडि", "पछाडि", "दायाँ", "बायाँ",
    "ठूलो", "सानो", "अग्लो", "होचो", "मोटो", "पातलो",
    "छिटो", "ढिलो", "राम्रो", "नराम्रो", "सजिलो", "गाह्रो",
    "तातो", "चिसो", "नुनिलो", "मिठो", "तितो", "अमिलो",
    "मेरो", "तिम्रो", "उसको", "हाम्रो", "तपाईंको", "उहाँको",
    "आफ्नो", "सबको", "केही", "सबै", "कोही", "कसैले",
    "जस्तो", "जति", "यति", "त्यति", "कति",
    "हुन्छ त", "भयो त", "गयो", "आयो", "लियो",
    "लिएर", "गएर", "आएर", "गरेर", "भनेर",
    "सायद", "पक्कै", "जरुर", "अवश्य", "निश्चित",
    "तर", "किनकि", "र", "वा", "पनि", "नि", "त",

    # Common Hindi/Urdu loanwords used in everyday Nepali speech
    "अच्छा", "बिल्कुल", "जरूर", "सही", "गलत",
    "खुशी", "दुःख", "प्यार", "दोस्ती", "रिश्ता",
    "जिन्दगी", "दुनिया", "इन्सान", "वक्त", "वक़्त",
    "मौका", "काम", "काम आउनु", "हिम्मत", "जोश",
    "इज्जत", "शुक्रिया", "माफी", "माफ करना",
    "यार", "बहुत बढिया", "जबरदस्त", "कमाल",
    "बेकार छैन", "जादू", "तमाशा", "खेलकुद",
    "जरूरत", "मतलब", "फिकर", "चिन्ता छैन",
    "समझदार", "बुद्धिमान", "होशियार", "चतुर",
    "मेहनती", "लगनशील", "ईमानदार", "सच्चा",

    # Romanized Nepali (safe words people commonly type in Roman script)
    "ramro", "ramri", "sanchai", "thik cha", "thik chha",
    "huncha", "hunchha", "bhayo", "bhena", "chha", "chhan",
    "dhanyabad", "danyabad", "namaskar", "namaste",
    "hajur", "tapai", "tapain", "timro", "mero", "hamro",
    "yaar", "bhai", "didi", "dai", "baini",
    "kasto cha", "ke cha", "kaha cha", "kaha janu",
    "khana", "paani", "pani", "ghar", "gau", "shahar",
    "sathi", "saathi", "mitra", "dost", "saathiharu",
    "maya", "maaya", "prem", "pyar", "sneha",
    "masto", "mast", "dherai", "ali ali", "thorai",
    "aaunus", "aau", "janus", "jau", "basa", "uthnus",
    "garnus", "garau", "bhannus", "sunu", "hernu",
    "khel", "naach", "geet", "sangeet", "kela",
    "padhnu", "lekhnu", "sikhnu", "bujhnu", "sodhnu",
    "khusi", "khushi", "dukha", "pida", "sukha",
    "safal", "safalta", "asafal", "prayas", "koshish",
    "sundar", "sundari", "ramri", "siddha", "sahi",
    "bistaro", "bistare", "chito", "dhilo", "pachi",
    "aja", "hijo", "bholi", "bihana", "sanjha", "raat",
    "sabai", "sab", "kehi", "kohi", "kasle", "kasai",
    "yo", "tyo", "yaha", "tyaha", "ahile", "pachi",
    "ho", "hoina", "haina", "hunchha", "hudaina",
    "asti", "agadi", "pachadi", "maathi", "tala",
    "thulo", "sano", "aglo", "hocho", "moto", "patlo",
    "tato", "chiso", "nunilo", "mitho", "tito", "amilo",
    "love", "care", "share", "friend", "family", "heart",


]


# OFFENSIVE / RUDE / VULGAR WORDS  (weighted dict – severity 0.0–1.0)

OFFENSIVE_WORDS = {

    # Nepali: General Insults (mild) 
    "मूर्ख":            0.30,
    "बेवकुफ":           0.30,
    "अज्ञानी":          0.25,
    "नासमझ":            0.25,
    "अबुझ":             0.20,
    "लठ्ठे":            0.25,
    "ढुंगे":            0.20,
    "गाई":              0.20,
    "गधा":              0.25,
    "गदहा":             0.25,
    "बाँदर":            0.25,
    "बँदर":             0.25,
    "सुँगुर":           0.30,
    "कुकुर":            0.30,
    "भेडा":             0.20,
    "खच्चड":            0.25,
    "पशु":              0.25,
    "जनावर":            0.25,
    "हैवान":            0.40,
    "राक्षस":           0.40,
    "बदमास":            0.35,
    "बदचलन":            0.35,
    "बेशर्म":           0.40,
    "निर्लज्ज":         0.40,
    "ढाँटे":            0.30,
    "झुठो":             0.30,
    "ठगी":              0.40,
    "धोकेबाज":          0.45,
    "छलिया":            0.35,
    "मक्कार":           0.40,
    "स्वार्थी":         0.30,
    "खोटो":             0.30,
    "नराम्रो":          0.20,
    "खराब":             0.25,
    "भ्रष्ट":           0.35,
    "भ्रष्टाचारी":      0.40,
    "दुराचारी":         0.40,
    "अनैतिक":           0.30,
    "पापी":             0.30,
    "पाखण्डी":          0.35,
    "ढोंगी":            0.30,
    "नाटकी":            0.25,
    "आडम्बरी":          0.25,
    "मिथ्यावादी":       0.35,
    "चाप्लुस":          0.25,
    "चमचा":             0.25,
    "खुसामदी":          0.20,
    "तेलमारे":          0.20,
    "भड्किलो":          0.20,
    "फटाहा":            0.40,
    "साला":             0.50,
    "सालो":             0.50,
    "सालाको":           0.50,
    "मुजी":             0.70,
    "खाते":             0.60,
    "कमिना":            0.60,
    "कमजात":            0.65,
    "नालायक":           0.40,
    "घृणित":            0.40,
    "चरित्रहीन":        0.50,
    "अधम":              0.50,
    "पतित":             0.45,
    "नीच":              0.50,
    "दुर्जन":           0.45,
    "दुष्ट":            0.50,
    "क्रूर":            0.55,
    "कठोर":             0.30,
    "निर्दयी":          0.40,
    "बेरहम":            0.45,
    "विश्वासघाती":      0.55,
    "गद्दार":           0.60,
    "देशद्रोही":        0.60,
    "दगाबाज":           0.50,
    "चोर":              0.45,
    "डाकू":             0.55,
    "लुटेरा":           0.55,
    "हरामी":            0.70,
    "हराम":             0.65,
    "बेकार":            0.30,
    "निकम्मो":          0.35,
    "कुरूप":            0.35,
    "बदसूरत":           0.35,
    "भद्दा":            0.30,
    "बिग्रेको":         0.30,
    "लाज मर्यो":        0.45,
    "लज्जास्पद":        0.40,
    "शर्मनाक":          0.40,
    "घिनलाग्दो":        0.45,
    "बेइज्जत":          0.45,

    #  Nepali: Discriminatory / Casteist Slurs
    "धोती":             0.70,
    "भते":              0.70,
    "पहाडे":            0.60,
    "मधेसे":            0.55,
    "जात खाने":         0.70,
    "जातीय भेदभाव":     0.65,

    #  Nepali: Additional rude/offensive 
    "बेइज्जती":         0.45,
    "अपमान":            0.40,
    "तिरस्कार":         0.40,
    "घृणा":             0.45,
    "वैर":              0.40,
    "दुश्मनी":          0.40,
    "झगडालु":           0.30,
    "कलहकारी":          0.30,
    "दङ्गाबाज":         0.45,
    "उपद्रवी":          0.35,
    "ठग":               0.45,
    "अहंकारी":          0.30,
    "घमण्डी":           0.30,
    "अभिमानी":          0.25,
    "बदतमिज":           0.40,
    "बेअदब":            0.40,
    "असभ्य":            0.35,
    "अशिष्ट":           0.35,
    "उदण्ड":            0.35,
    "बागी":             0.35,
    "अराजक":            0.40,
    "बेकानुनी":         0.40,
    "अवैध":             0.35,
    "अमर्यादित":        0.35,
    "गालीगलौज":         0.45,

    # Nepali: Additional common offensive words that were missing
    "रन्डी":            0.80,
    "रण्डी":            0.80,
    "छिनाल":            0.80,
    "छिनाली":           0.80,
    "कुलटा":            0.75,
    "वेश्या":           0.80,
    "छक्का":            0.60,
    "हिजडा":            0.65,
    "हिजड़ा":           0.65,
    "मोटी":             0.35,
    "मोटो":             0.30,
    "काली":             0.40,
    "गोरी":             0.20,
    "बूढो":             0.20,
    "बूढी":             0.20,
    "डल्ले":            0.35,
    "ढुल्के":           0.30,
    "भुण्डे":           0.35,
    "ठुट्टे":           0.30,
    "लम्पट":            0.55,
    "व्यभिचारी":        0.60,
    "बदचलनी":           0.40,
    "चरित्रहीना":       0.55,
    "असभ्य":            0.35,
    "अश्लील":           0.50,
    "भद्दा":            0.30,
    "गन्दा":            0.40,
    "झुट्टो":           0.30,
    "ढाँटेको":          0.30,
    "घटिया":            0.40,
    "कमजोर":            0.20,
    "डरपोक":            0.35,
    "कायर":             0.40,
    "भागेको":           0.20,
    "पठ्ठो":            0.30,
    "बुद्धू":           0.30,
    "अहमक":             0.35,
    "उल्लु":            0.30,
    "मठ्ठो":            0.25,
    "ढाटे":             0.30,
    "झुठे":             0.30,
    "नमर्द":            0.55,
    "नपुंसक":           0.55,
    "बेकम्मा":          0.35,
    "खाली ठाउँ":        0.25,
    "बेरोजगार":         0.15,
    "ठग": 0.45,
    "धोकेबाज": 0.45,
    "पाखे":             0.45,
    "गन्वार":           0.40,
    "जाहिल":            0.35,
    "अनपढ":             0.30,
    "जंगली":            0.40,
    "काफर":             0.55,
    "म्लेच्छ":          0.55,
    "जात मार्ने":       0.65,
    "जात गएको":         0.60,
    "बहिनी चिक्ने":     0.85,
    "आमा चिक्ने":       0.90,
    "बाउ को":           0.45,
    "तेरो आमाको":       0.65,
    "तेरो बाउको":       0.60,
    "तेरी आमा":         0.65,
    "तेरो बाप":         0.55,

    # English: Mild/Moderate Insults 
    "stupid":           0.30,
    "idiot":            0.35,
    "moron":            0.35,
    "imbecile":         0.35,
    "dimwit":           0.30,
    "dumb":             0.25,
    "dull":             0.20,
    "brainless":        0.30,
    "witless":          0.30,
    "clueless":         0.25,
    "fool":             0.25,
    "foolish":          0.25,
    "buffoon":          0.30,
    "clown":            0.25,
    "nitwit":           0.30,
    "blockhead":        0.30,
    "bonehead":         0.30,
    "knucklehead":      0.30,
    "airhead":          0.25,
    "birdbrain":        0.25,
    "jerk":             0.40,
    "loser":            0.35,
    "failure":          0.30,
    "pathetic":         0.40,
    "useless":          0.35,
    "worthless":        0.40,
    "hopeless":         0.30,
    "incompetent":      0.30,
    "incapable":        0.30,
    "inept":            0.30,
    "lazy":             0.25,
    "slacker":          0.25,
    "coward":           0.35,
    "wimp":             0.30,
    "crybaby":          0.25,
    "whiner":           0.25,
    "liar":             0.40,
    "cheat":            0.40,
    "fraud":            0.45,
    "fake":             0.35,
    "phony":            0.35,
    "hypocrite":        0.40,
    "two-faced":        0.45,
    "backstabber":      0.50,
    "traitor":          0.55,
    "snitch":           0.40,
    "creep":            0.45,
    "weirdo":           0.30,
    "freak":            0.35,
    "oddball":          0.25,
    "nutcase":          0.35,
    "psycho":           0.40,
    "maniac":           0.40,
    "lunatic":          0.40,
    "wacko":            0.35,
    "crazy":            0.25,
    "rude":             0.30,
    "obnoxious":        0.40,
    "annoying":         0.25,
    "irritating":       0.25,
    "infuriating":      0.35,
    "disgusting":       0.45,
    "revolting":        0.45,
    "repulsive":        0.45,
    "vile":             0.55,
    "vulgar":           0.45,
    "obscene":          0.55,
    "indecent":         0.45,
    "shameless":        0.45,
    "disrespectful":    0.40,
    "insolent":         0.40,
    "impudent":         0.40,
    "arrogant":         0.35,
    "conceited":        0.30,
    "pompous":          0.30,
    "narcissistic":     0.35,
    "selfish":          0.30,
    "greedy":           0.30,
    "manipulative":     0.50,
    "controlling":      0.40,
    "abusive":          0.60,
    "toxic":            0.50,
    "corrupt":          0.45,
    "immoral":          0.40,
    "unethical":        0.40,
    "dishonest":        0.40,
    "deceitful":        0.45,
    "deceptive":        0.45,
    "treacherous":      0.55,
    "untrustworthy":    0.40,
    "irresponsible":    0.30,
    "immature":         0.25,
    "childish":         0.25,
    "petty":            0.25,
    "spiteful":         0.40,
    "vindictive":       0.45,
    "bitter":           0.30,
    "resentful":        0.30,
    "jealous":          0.25,
    "envious":          0.25,
    "nasty":            0.45,
    "mean":             0.40,
    "cruel":            0.55,
    "heartless":        0.50,
    "insensitive":      0.35,
    "callous":          0.40,
    "ignorant":         0.35,
    "prejudiced":       0.50,
    "biased":           0.40,
    "discriminatory":   0.55,
    "racist":           0.70,
    "sexist":           0.65,
    "bigot":            0.65,
    "bully":            0.55,
    "thug":             0.50,
    "criminal":         0.50,
    "delinquent":       0.45,
    "scammer":          0.50,
    "swindler":         0.50,
    "lowlife":          0.55,
    "scoundrel":        0.50,
    "villain":          0.50,
    "crook":            0.50,
    "degenerate":       0.55,
    "garbage":          0.45,
    "trash":            0.45,
    "rubbish":          0.35,
    "waste":            0.30,
    "junk":             0.25,
    "awful":            0.35,
    "atrocious":        0.40,
    "dreadful":         0.35,
    "horrible":         0.40,
    "terrible":         0.35,
    "lousy":            0.30,
    "mediocre":         0.20,
    "inferior":         0.30,
    "shoddy":           0.30,
    "abysmal":          0.40,
    "disgraceful":      0.45,
    "outrageous":       0.40,
    "scandalous":       0.45,
    "ugly":             0.35,
    "hideous":          0.40,
    "grotesque":        0.40,
    "ghastly":          0.40,
    "foul":             0.40,
    "rotten":           0.40,
    "filthy":           0.40,
    "dirty":            0.30,
    "slimy":            0.35,
    "scummy":           0.45,
    "despicable":       0.55,

    #  English: Rude Exclamations (moderate) 
    "get lost":         0.40,
    "get out":          0.35,
    "buzz off":         0.35,
    "back off":         0.30,
    "leave me alone":   0.25,
    "none of your business": 0.25,
    "drop dead":        0.60,
    "get a life":       0.30,
    "what's wrong with you": 0.30,

    #  English: Additional offensive adjectives 
    "abrasive":         0.30,
    "aggravating":      0.30,
    "aggressive":       0.40,
    "antagonistic":     0.45,
    "appalling":        0.45,
    "asinine":          0.35,
    "audacious":        0.25,
    "bad-tempered":     0.30,
    "banal":            0.20,
    "barbaric":         0.55,
    "boorish":          0.35,
    "brash":            0.30,
    "brazen":           0.35,
    "brutal":           0.55,
    "careless":         0.25,
    "caustic":          0.40,
    "condescending":    0.45,
    "contemptible":     0.50,
    "contentious":      0.35,
    "crabby":           0.25,
    "cranky":           0.25,
    "crass":            0.40,
    "crude":            0.40,
    "cynical":          0.30,
    "debased":          0.45,
    "decadent":         0.35,
    "defiant":          0.30,
    "demeaning":        0.50,
    "demoralizing":     0.45,
    "deplorable":       0.50,
    "depraved":         0.60,
    "destructive":      0.50,
    "devious":          0.45,
    "disruptive":       0.35,
    "divisive":         0.45,
    "exploitative":     0.55,
    "fanatical":        0.55,
    "hostile":          0.50,
    "hypocritical":     0.40,
    "inflammatory":     0.50,
    "insulting":        0.50,
    "irrational":       0.30,
    "judgmental":       0.35,
    "malicious":        0.60,
    "mean-spirited":    0.50,
    "misleading":       0.40,
    "mockery":          0.35,
    "negative":         0.25,
    "negligent":        0.35,
    "oppressive":       0.60,
    "patronizing":      0.40,
    "reckless":         0.35,
    "self-centered":    0.30,
    "shallow":          0.25,
    "stubborn":         0.25,
    "tactless":         0.30,
    "thoughtless":      0.30,
    "troublesome":      0.30,
    "uncouth":          0.35,
    "unkind":           0.30,
    "unreasonable":     0.30,
    "unruly":           0.35,
    "unscrupulous":     0.50,
    "vain":             0.25,
    "volatile":         0.40,
}

# HATEFUL / THREATENING / VIOLENT WORDS  (weighted dict – severity 0.0–1.0)

HATEFUL_WORDS = {

    # Nepali: Threats & Violence 
    "मार्छु":           0.95,
    "मार्ने":           0.90,
    "मारिदिन्छु":       0.98,
    "मारिदिउँ":         0.95,
    "मारिहाल्छु":       0.95,
    "काट्छु":           0.90,
    "काट्ने":           0.85,
    "काटिदिन्छु":       0.93,
    "काटिहाल्छु":       0.92,
    "मरोस्":            0.80,
    "मरिजाओस्":         0.80,
    "मरिजा":            0.80,
    "मर":               0.75,
    "जलाउँछु":          0.88,
    "जलाइदिन्छु":       0.90,
    "डुबाउँछु":         0.88,
    "फेकिदिन्छु":       0.82,
    "पुरिदिन्छु":       0.88,
    "मुठ्ठी हिर्काउँछु": 0.85,
    "पिट्छु":           0.80,
    "कुट्छु":           0.80,
    "ठोक्छु":           0.82,
    "धकेल्छु":          0.72,
    "घाइते गर्छु":      0.88,
    "अपाङ्ग बनाउँछु":  0.90,
    "सखाप पार्छु":      0.88,
    "समाप्त गर्छु":     0.87,
    "ध्वंस गर्छु":      0.85,
    "बर्बाद गर्छु":     0.82,
    "नाश गर्छु":        0.82,
    "खत्म गर्छु":       0.85,
    "मेटाउँछु":         0.80,
    "नष्ट गर्छु":       0.82,
    "रगत बगाउँछु":      0.95,
    "रगत गिराउँछु":     0.93,
    "टुक्रा पार्छु":    0.93,
    "हात काट्छु":       0.92,
    "खुट्टा काट्छु":    0.92,
    "टाउको फोड्छु":     0.95,
    "आँखा फोड्छु":      0.92,
    "गर्दन काट्छु":     0.97,
    "हड्डी भाँच्छु":    0.88,
    "लास बनाउँछु":      0.97,
    "लाश पार्छु":       0.97,
    "माटोमा मिसाउँछु":  0.95,
    "कंकाल बनाउँछु":    0.95,

    #  Nepali: Death Wishes & Extreme Hate 
    "मर्स्या":          0.80,
    "मरी जाओस्":        0.82,
    "नरकमा जाओस्":      0.78,
    "बरबाद होस्":       0.72,
    "तबाह होस्":        0.75,
    "ध्वस्त होस्":      0.75,
    "नाश होस्":         0.75,
    "मसान होस्":        0.80,
    "चिहान जाओस्":      0.82,
    "मर्नु नै राम्रो":  0.85,
    "श्राप":            0.60,
    "अभिशाप":           0.62,
    "भस्म होस्":        0.78,
    "आगो लागोस्":       0.80,
    "विष खाओस्":        0.85,
    "डुबेर मर":         0.90,
    "गोली लागोस्":      0.88,
    "दुर्घटनामा मरोस्": 0.88,
    "एक्लो मर":         0.80,
    "दुखेर मर":         0.82,

    #  Nepali: Incitement & Extremism 
    "हमला गर":          0.90,
    "आक्रमण गर":        0.88,
    "बमबारी गर":        0.97,
    "विस्फोट गर":       0.95,
    "दंगा गर":          0.90,
    "आगो लगाओ":         0.88,
    "जलाओ":             0.85,
    "लुट":              0.80,
    "डाका":             0.82,
    "अपहरण":            0.85,
    "हत्या गर":         1.00,
    "हत्यारा":          0.88,
    "आतंकवाद":          0.92,
    "आतंकवादी":         0.90,
    "नरसंहार":          1.00,
    "जनजाति सफाया":     1.00,
    "जातीय हिंसा":      0.92,
    "साम्प्रदायिक दंगा": 0.90,
    "धार्मिक घृणा":     0.85,
    "जिहाद":            0.88,
    "धर्मयुद्ध":        0.85,
    "फाँसी दे":         0.88,
    "मृत्युदण्ड":       0.85,

    #  Nepali: Extreme slurs & targeting 
    "रगत पिउँछु":       0.95,
    "हड्डी चुस्छु":     0.90,
    "निशान नराख्ने":    0.92,
    "पत्तो नलाग्ने":    0.88,
    "अधम जात":          0.80,
    "नीच जात":          0.82,
    "पतित जात":         0.80,

    #  Nepali: Additional hate/threat 
    "बदला लिन्छु":      0.85,
    "माफ गर्दिनँ":      0.70,
    "जीवनभर सताउँछु":  0.82,
    "चैन दिँदिनँ":      0.72,
    "हानि पुर्‍याउँछु": 0.80,
    "विनाश":            0.72,
    "सर्वनाश":          0.78,
    "प्रलय":            0.70,
    "भस्म":             0.75,
    "चेतावनी दिन्छु":  0.65,
    "भोगिहाल्छस्":      0.70,
    "जिन्दगी बर्बाद हुन्छ": 0.75,
    "भविष्य अन्धकार":  0.70,
    "विपत्ति आओस्":     0.72,
    "मृत्यु होस्":      0.88,
    "असमय मृत्यु":      0.90,
    "दुर्मरण होस्":     0.90,
    "जातीय विभाजन":     0.82,
    "साम्प्रदायिक घृणा": 0.85,
    "धार्मिक कट्टरता":  0.80,
    "अतिवाद":           0.80,
    "उग्रवाद":          0.85,
    "आतंक":             0.88,
    "भय फैलाउ":         0.82,
    "दहशत":             0.80,
    "आतंकित गर":        0.85,

    #  English: Direct Threats 
    "kill":             0.90,
    "murder":           0.92,
    "slay":             0.85,
    "slaughter":        0.90,
    "execute":          0.85,
    "assassinate":      0.95,
    "eliminate":        0.80,
    "terminate":        0.78,
    "destroy":          0.75,
    "annihilate":       0.90,
    "obliterate":       0.88,
    "eradicate":        0.85,
    "wipe out":         0.88,
    "finish off":       0.82,
    "exterminate":      0.92,
    "massacre":         0.95,
    "butcher":          0.90,
    "liquidate":        0.88,
    "hunt down":        0.85,
    "i will kill you":  1.00,
    "i will hurt you":  0.95,
    "i will destroy you": 0.90,
    "you are dead":     0.88,
    "you will pay":     0.80,
    "i know where you live": 0.90,
    "watch your back":  0.82,
    "your time is up":  0.85,
    "end is near":      0.78,
    "nowhere to hide":  0.82,
    "i will make you suffer": 0.92,
    "you will suffer":  0.88,
    "hurt":             0.72,
    "harm":             0.70,
    "injure":           0.72,
    "wound":            0.72,
    "maim":             0.85,
    "cripple":          0.82,
    "disfigure":        0.85,
    "torture":          0.92,
    "mutilate":         0.92,
    "dismember":        0.95,
    "behead":           0.97,
    "strangle":         0.92,
    "suffocate":        0.90,
    "drown":            0.85,
    "stab":             0.88,
    "shoot":            0.88,
    "bomb":             0.88,
    "poison":           0.82,
    "hang":             0.85,
    "decapitate":       0.97,
    "beat to death":    0.97,

    #  English: Hate Speech & Extremism 
    "hate speech":      0.80,
    "extremism":        0.80,
    "terrorism":        0.92,
    "terrorist":        0.90,
    "genocide":         1.00,
    "ethnic cleansing": 1.00,
    "holocaust":        0.95,
    "massacre":         0.95,
    "war crimes":       0.90,
    "jihad":            0.88,
    "holy war":         0.85,
    "death squad":      0.92,
    "lynch mob":        0.92,
    "white supremacy":  0.92,
    "supremacist":      0.90,
    "nazi":             0.92,
    "fascist":          0.85,
    "neo-nazi":         0.95,
    "ethnic hatred":    0.88,
    "racial hatred":    0.88,
    "religious hatred": 0.85,
    "sectarian violence": 0.90,
    "incite violence":  0.92,
    "incite hatred":    0.90,
    "call to violence": 0.92,
    "insurrection":     0.82,
    "armed revolt":     0.85,
    "bomb threat":      0.95,
    "death threat":     0.98,
    "die slowly":       0.90,
    "rot in hell":      0.82,
    "burn in hell":     0.82,
    "go to hell":       0.70,
    "damned":           0.60,
    "cursed":           0.58,
    "doomed":           0.60,
    "vermin":           0.85,
    "parasite":         0.75,
    "plague":           0.78,
    "cancer":           0.72,
    "cockroach":        0.88,
    "rat":              0.65,
    "pig":              0.60,
    "beast":            0.65,
    "monster":          0.65,
    "demon":            0.65,
    "devil":            0.62,
    "subhuman":         0.92,
    "inhuman":          0.80,
    "savage":           0.78,
    "barbarian":        0.72,
    "inferior race":    0.95,
    "lesser being":     0.90,
    "not human":        0.92,
    "waste of space":   0.82,
    "waste of life":    0.85,
    "should not exist": 0.90,
    "world better without": 0.88,
    "do everyone a favor die": 1.00,

    # English: Violent Threats 
    "bash your skull":  0.97,
    "break your neck":  0.97,
    "snap your neck":   0.97,
    "put a bullet in":  0.97,
    "blow your head off": 1.00,
    "cut your throat":  0.98,
    "slit your wrists": 0.90,
    "deserves to die":  0.90,
    "should be dead":   0.88,
    "better off dead":  0.85,
    "end yourself":     0.90,
    "remove yourself":  0.82,
    "jump off a bridge": 0.90,
    "go play in traffic": 0.85,
    "drink bleach":     0.92,
    "eat glass":        0.88,
    "set yourself on fire": 0.95,
    "put a gun to your head": 0.97,
    "do the world a favor": 0.80,
    "take yourself out": 0.85,
    "no one will miss you": 0.82,
    "nobody wants you": 0.78,
    "you are worthless trash": 0.85,

    # English: Dehumanizing 
    "not a real person": 0.88,
    "plague on society": 0.82,
    "cancer of society": 0.82,
    "infestation":      0.80,
    "they are animals": 0.85,
    "they are cockroaches": 0.92,
    "they are rats":    0.88,
    "exterminate them": 0.95,
    "get rid of them":  0.80,
    "purge them":       0.88,
    "cleanse the earth": 0.92,
    "cleanse society":  0.90,
    "they don't deserve rights": 0.88,
    "strip them of rights": 0.85,
    "deport them all":  0.80,
    "round them up":    0.82,
    "gas them":         0.97,
    "they are inferior": 0.88,
    "they pollute our culture": 0.82,

    # English: Incitement & Calls to Violence 
    "attack":           0.80,
    "assault":          0.82,
    "raid":             0.78,
    "ambush":           0.80,
    "hit them":         0.80,
    "beat them":        0.82,
    "mob them":         0.85,
    "gang up":          0.78,
    "go after them":    0.82,
    "target them":      0.80,
    "make their life hell": 0.80,
    "harass them":      0.78,
    "stalk them":       0.82,
    "doxx them":        0.85,
    "ruin their life":  0.80,
    "take revenge":     0.75,
    "payback time":     0.72,
    "burn their house": 0.90,
    "torch their car":  0.88,
    "smash their windows": 0.80,
    "destroy their property": 0.82,
    "sabotage":         0.72,
    "vandalize":        0.72,

    #  English: Additional extreme hate terms 
    "bludgeon":         0.88,
    "brutalize":        0.88,
    "carnage":          0.85,
    "combust":          0.75,
    "crush":            0.72,
    "decimate":         0.82,
    "demolish":         0.72,
    "devastate":        0.72,
    "dispose of":       0.75,
    "dominate by force": 0.80,
    "enslave":          0.85,
    "extirpate":        0.88,
    "flay":             0.90,
    "force upon":       0.82,
    "gut":              0.82,
    "hunt":             0.78,
    "incinerate":       0.85,
    "invoke terror":    0.90,
    "lay waste":        0.82,
    "maul":             0.85,
    "mutilate":         0.92,
    "nuke":             0.88,
    "oppress":          0.80,
    "persecute":        0.85,
    "plunder":          0.78,
    "pulverize":        0.82,
    "purge":            0.85,
    "rampage":          0.82,
    "ravage":           0.82,
    "raze":             0.82,
    "reign of terror":  0.92,
    "rip apart":        0.88,
    "rupture":          0.75,
    "scorch":           0.78,
    "sever":            0.80,
    "shred":            0.80,
    "silence permanently": 0.85,
    "smash":            0.72,
    "snuff out":        0.85,
    "subjugate":        0.80,
    "suppress by force": 0.82,
    "systematic killing": 0.95,
    "tear apart":       0.85,
    "terror attack":    0.95,
    "torch":            0.80,
    "total destruction": 0.85,
    "unleash violence": 0.88,
    "violent act":      0.80,
    "violent crime":    0.82,
    "violent uprising": 0.85,
    "weaponize":        0.82,
}


# OFFENSIVE SUBCATEGORIES  (for analytics / flagged-words chart breakdowns)

OFFENSIVE_SUBCATEGORIES = {
    "casteist": [
        "धोती", "भते", "पहाडे", "मधेसे", "दलित", "हरिजन",
        "जात खाने", "जातीय भेदभाव", "अधम जात", "नीच जात",
    ],
    "misogynist": [
        "रण्डी", "छिनाल",  # detection only
    ],
    "body_shame": [
        "कुरूप", "बदसूरत", "भद्दा", "ugly", "hideous", "grotesque", "unsightly",
    ],
    "slurs": [
        "मुजी", "खाते", "कमिना", "कमजात", "हरामी", "साला", "सालो",
        "thug", "lowlife", "scoundrel",
    ],
    "general": [
        "मूर्ख", "गधा", "गदहा", "बेवकुफ", "नालायक", "बेकार",
        "stupid", "idiot", "moron", "fool", "loser", "jerk",
    ],
    "discrimination": [
        "racist", "sexist", "bigot", "prejudiced", "discriminatory",
        "oppressive", "biased",
    ],
}


# HATEFUL SUBCATEGORIES  (for analytics / flagged-words chart breakdowns)

HATEFUL_SUBCATEGORIES = {
    "direct_threat": [
        "मार्छु", "काट्छु", "मारिदिन्छु", "घाइते गर्छु", "पिट्छु",
        "kill", "stab", "shoot", "hurt", "harm", "attack", "assault",
    ],
    "death_wish": [
        "मरोस्", "मरिजाओस्", "नरकमा जाओस्", "मर्नु नै राम्रो",
        "rot in hell", "burn in hell", "die slowly", "better off dead",
        "deserves to die", "should be dead",
    ],
    "incitement": [
        "हमला गर", "दंगा गर", "आगो लगाओ", "हत्या गर", "बमबारी गर",
        "riot", "attack", "bomb", "incite violence", "call to violence",
        "insurrection", "armed revolt",
    ],
    "dehumanizing": [
        "जनावर", "सुँगुर", "कुकुर",
        "vermin", "cockroach", "subhuman", "parasite",
        "they are animals", "inferior race", "not human",
    ],
    "extremist": [
        "आतंकवाद", "आतंकवादी", "नरसंहार", "जिहाद",
        "terrorism", "terrorist", "genocide", "ethnic cleansing",
        "nazi", "white supremacy", "neo-nazi", "fascist",
    ],
}



# OFFENSIVE PHRASES  (multi-word – caught by phrase-level scan, not token scan)

OFFENSIVE_PHRASES = [
    # Nepali
    "मुख बन्द गर",
    "बोल्न लायक छैनस्",
    "कुन मुखले",
    "लाज मर्यो",
    "हेर्न पनि मन लाग्दैन",
    "तँ के हो र",
    "किन छस् यहाँ",
    "टाढा हट",
    "भागिजा",
    "सुन्छस् कि सुन्दैनस्",
    "मुख छैन तँलाई",
    "खराब संस्कार",
    "तँलाई शर्म लाग्दैन",
    "आफ्नो काम गर",
    # English
    "shut up",
    "get lost",
    "who do you think you are",
    "get a life",
    "what's wrong with you",
    "you are such a loser",
    "nobody likes you",
    "you are pathetic",
    "mind your own business",
    "butt out",
    "stay out of it",
    "you think you know everything",
    "what a mess",
    "what a disaster",
    "pathetic excuse",
    "you are worthless",
    "such a disappointment",
    "grow up",
    "act your age",
    "you're embarrassing yourself",
]


# HATEFUL PHRASES  (multi-word – caught by phrase-level scan, not token scan)

HATEFUL_PHRASES = [
    # Nepali
    "तँलाई मारिदिन्छु",
    "रगत बगाउँछु",
    "टुक्रा पारिदिन्छु",
    "लास बनाउँछु",
    "माटोमा मिलाउँछु",
    "कंकाल बनाउँछु",
    "मुठ्ठी हिर्काउँछु",
    "हात काट्छु",
    "गर्दन काट्छु",
    "टाउको फोड्छु",
    "घरबाट थुतेर मार्छु",
    "तेरो दिन गन्ती सुरु भयो",
    "तँलाई सखाप पार्छु",
    "जीवनबाट हटाउँछु",
    "रगत गिराउँछु",
    # English
    "i will kill you",
    "i will hurt you",
    "i will destroy you",
    "i will make you suffer",
    "you will pay for this",
    "watch your back",
    "your time is up",
    "do the world a favor and die",
    "drink bleach",
    "no one will miss you",
    "nobody wants you here",
    "you are dead to me",
    "end yourself",
    "go play in traffic",
    "jump off a bridge",
    "put a bullet in your head",
    "cut your throat",
    "bash your skull",
    "break your neck",
    "blow your head off",
    "i know where you live",
    "nowhere to hide",
    "you better run",
    "i'm coming for you",
    "your family will pay",
]



# ROMANIZED NEPALI MAP  { romanized_form: devanagari_equivalent }
# The classifier should transliterate before checking OFFENSIVE/HATEFUL dicts.

ROMANIZED_MAP = {
    # ── Threats ──────────────────────────────────────────────────────────────
    "marchu":           "मार्छु",
    "marichhu":         "मार्छु",
    "maridinchhu":      "मारिदिन्छु",
    "maridinchu":       "मारिदिन्छु",
    "marihalchhu":      "मारिहाल्छु",
    "marihalchu":       "मारिहाल्छु",
    "katchu":           "काट्छु",
    "kaatchu":          "काट्छु",
    "katidinchhu":      "काटिदिन्छु",
    "katidinchu":       "काटिदिन्छु",
    "pidinchhu":        "पिट्छु",
    "pitchhu":          "पिट्छु",
    "pitchu":           "पिट्छु",
    "kutchhu":          "कुट्छु",
    "kutchu":           "कुट्छु",
    "thokchhu":         "ठोक्छु",
    "thokchhhu":        "ठोक्छु",
    "thokchu":          "ठोक्छु",
    "jalainchhu":       "जलाउँछु",
    "jalauchu":         "जलाउँछु",
    "jalainchu":        "जलाउँछु",
    "sakhap":           "सखाप",
    "sakhap parchu":    "सखाप पार्छु",
    "sakhap parchhu":   "सखाप पार्छु",
    "hamla gar":        "हमला गर",
    "hamla":            "हमला",
    "hamala":           "हमला",
    "danga gar":        "दंगा गर",
    "danga":            "दंगा",
    "hatya gar":        "हत्या गर",
    "hatya":            "हत्या",
    "raktam bagauchu":  "रगत बगाउँछु",
    "ragat bagauchu":   "रगत बगाउँछु",
    "ragat bagainchhu": "रगत बगाउँछु",
    "las banauchu":     "लास बनाउँछु",
    "laas banauchu":    "लास बनाउँछु",
    "las banaunchhu":   "लास बनाउँछु",
    "dhakka dinu":      "धकेल्छु",
    "pita dinu":        "पिट्छु",
    "kuta dinu":        "कुट्छु",
    "ghait garchu":     "घाइते गर्छु",
    "mardinchhu":       "मारिदिन्छु",
    "mardichu":         "मारिदिन्छु",
    "badla linchhu":    "बदला लिन्छु",
    "badla linu":       "बदला लिन्छु",

    # ── Common Insults (all spelling variants) ────────────────────────────────
    # muji variants – most commonly searched / evaded word
    "muji":             "मुजी",
    "muj":              "मुजी",
    "muje":             "मुजी",
    "muzi":             "मुजी",
    "muzi":             "मुजी",
    "muj1":             "मुजी",
    "m u j i":          "मुजी",
    "m.u.j.i":          "मुजी",
    "muji ko":          "मुजी",
    "mujiko":           "मुजी",
    "muji le":          "मुजी",
    "muji lai":         "मुजी",
    "mujile":           "मुजी",
    "mujilai":          "मुजी",
    "mujee":            "मुजी",
    "moojiee":          "मुजी",
    "mooji":            "मुजी",
    "muzy":             "मुजी",
    "mujiiii":          "मुजी",

    # sala / saala variants
    "sala":             "साला",
    "saala":            "साला",
    "saalo":            "साला",
    "saala ko":         "साला",
    "salako":           "साला",
    "saalako":          "साला",
    "sala bhai":        "साला",
    "sala yaar":        "साला",
    "s4la":             "साला",
    "s.a.l.a":          "साला",

    # harami variants
    "harami":           "हरामी",
    "haraami":          "हरामी",
    "haraamee":         "हरामी",
    "haramee":          "हरामी",
    "harami ko":        "हरामी",
    "haramiko":         "हरामी",
    "haram":            "हराम",
    "hramee":           "हरामी",
    "h4rami":           "हरामी",

    # gadha variants
    "gadha":            "गधा",
    "gaadha":           "गधा",
    "gadaha":           "गधा",
    "gadha jasto":      "गधा",
    "gadhe":            "गधा",
    "gadhaa":           "गधा",

    # murkha variants
    "murkha":           "मूर्ख",
    "murkho":           "मूर्ख",
    "murkhe":           "मूर्ख",
    "murkho":           "मूर्ख",
    "murkha jasto":     "मूर्ख",
    "moorakh":          "मूर्ख",
    "moorakha":         "मूर्ख",
    "murakh":           "मूर्ख",
    "murkha chha":      "मूर्ख",

    # khate variants
    "khate":            "खाते",
    "khuate":           "खाते",
    "khaat":            "खाते",
    "khaate":           "खाते",
    "khateee":          "खाते",
    "khat3":            "खाते",

    # kamina variants
    "kamina":           "कमिना",
    "kameena":          "कमिना",
    "kameene":          "कमिना",
    "kamena":           "कमिना",
    "kaminaa":          "कमिना",
    "kamjat":           "कमजात",
    "kamjaat":          "कमजात",

    # nalayak variants
    "nalayak":          "नालायक",
    "naalayak":         "नालायक",
    "nalayaka":         "नालायक",
    "nalaik":           "नालायक",

    # bekaar variants
    "bekaar":           "बेकार",
    "bekar":            "बेकार",
    "be kaar":          "बेकार",
    "bekaare":          "बेकार",
    "bakwaas":          "बेकार",
    "bakawas":          "बेकार",

    # besharam variants
    "besharam":         "बेशर्म",
    "besaram":          "बेशर्म",
    "besharm":          "बेशर्म",
    "nisharam":         "निर्लज्ज",
    "nirlajja":         "निर्लज्ज",

    # randi / chhinal variants
    "randi":            "रण्डी",
    "raandi":           "रण्डी",
    "randee":           "रण्डी",
    "randy":            "रण्डी",
    "r4ndi":            "रण्डी",
    "chhinal":          "छिनाल",
    "chinal":           "छिनाल",
    "chhinaali":        "छिनाल",
    "chinali":          "छिनाल",
    "kulata":           "कुलटा",
    "veshya":           "वेश्या",
    "veshyaa":          "वेश्या",
    "vesya":            "वेश्या",

    # other common romanized insults
    "nikammo":          "निकम्मो",
    "nikamma":          "निकम्मो",
    "nikammo":          "निकम्मो",
    "dhoti":            "धोती",
    "bhate":            "भते",
    "pahade":           "पहाडे",
    "pahaade":          "पहाडे",
    "madhise":          "मधेसे",
    "madhesi":          "मधेसे",
    "fataaha":          "फटाहा",
    "fataha":           "फटाहा",
    "ghamandi":         "घमण्डी",
    "ghamindia":        "घमण्डी",
    "kurup":            "कुरूप",
    "khurup":           "कुरूप",
    "badsurat":         "बदसूरत",
    "jhuto":            "झुठो",
    "jhutta":           "झुठो",
    "jhuttaa":          "झुठो",
    "chor":             "चोर",
    "dhokebaaz":        "धोकेबाज",
    "dhokebaj":         "धोकेबाज",
    "thagg":            "ठग",
    "thag":             "ठग",
    "chhali":           "छलिया",
    "makkar":           "मक्कार",
    "gaddar":           "गद्दार",
    "ghaddar":          "गद्दार",
    "bewakuf":          "बेवकुफ",
    "bewkoof":          "बेवकुफ",
    "bevakoof":         "बेवकुफ",
    "ullu":             "उल्लु",
    "pagle":            "पागल",
    "pagal":            "पागल",
    "paglo":            "पागल",
    "darpok":           "डरपोक",
    "kaayal":           "कायर",
    "kayar":            "कायर",
    "baiman":           "बेईमान",
    "be-iman":          "बेईमान",
    "beiman":           "बेईमान",
    "pakhe":            "पाखे",
    "gawar":            "गन्वार",
    "gawaar":           "गन्वार",
    "jahil":            "जाहिल",
    "jangli":           "जंगली",
    "lampad":           "लम्पट",
    "lampat":           "लम्पट",
    "vyabhichari":      "व्यभिचारी",
    "chakka":           "छक्का",
    "hijada":           "हिजडा",
    "hijra":            "हिजडा",
    "nijda":            "हिजडा",
    "aandhi":           "अन्धो",
    "bhrashtachari":    "भ्रष्टाचारी",
    "bhrastachari":     "भ्रष्टाचारी",
    "durachar":         "दुराचारी",
    "paapi":            "पापी",
    "pakhandee":        "पाखण्डी",
    "dhongi":           "ढोंगी",
    "natak baje":       "नाटकी",
    "chamcha":          "चमचा",
    "chaplush":         "चाप्लुस",
    "khushamadi":       "खुसामदी",
    "telmaar":          "तेलमारे",
    "ghinlagdo":        "घिनलाग्दो",
    "beizzat":          "बेइज्जत",
    "apmaan":           "अपमान",
    "nafrat":           "घृणा",
    "nafrat garchhu":   "घृणा",
    "gali dinu":        "गालीगलौज",
    "gali garchhu":     "गालीगलौज",
    "gaali":            "गालीगलौज",
    "gaalii":           "गालीगलौज",

    # ── Tera/Tero ("your __") offensive combos ──────────────────────────────
    "teri aama":        "तेरी आमा",
    "teri maa":         "तेरी आमा",
    "tero bau":         "तेरो बाउको",
    "tero bauko":       "तेरो बाउको",
    "teri aama ko":     "तेरी आमा",
    "teri mako":        "तेरी आमा",
    "aama chikne":      "आमा चिक्ने",
    "ama chikne":       "आमा चिक्ने",
    "bahini chikne":    "बहिनी चिक्ने",
    "didi chikne":      "बहिनी चिक्ने",

    # ── Death wishes ─────────────────────────────────────────────────────────
    "maros":            "मरोस्",
    "marosa":           "मरोस्",
    "marija":           "मरिजा",
    "mari ja":          "मरिजा",
    "marijaos":         "मरिजाओस्",
    "mar":              "मर",
    "mar ja":           "मरिजा",
    "narkama":          "नरकमा",
    "narkama jaos":     "नरकमा जाओस्",
    "narkama jaa":      "नरकमा जाओस्",
    "marnu nai ramro":  "मर्नु नै राम्रो",
    "marna nai ramro":  "मर्नु नै राम्रो",
    "mara":             "मर",
    "maro":             "मरोस्",
    "hatya garideu":    "हत्या गर",
    "hatya garnu":      "हत्या गर",
    "jala deu":         "जलाउँछु",
    "jalaideu":         "जलाउँछु",
    "barbaad hos":      "बरबाद होस्",
    "barbad hos":       "बरबाद होस्",
    "naash hos":        "नाश होस्",
    "tabbah hos":       "तबाह होस्",
    "dhwasta hos":      "ध्वस्त होस्",
    "mritu hos":        "मृत्यु होस्",

    # ── Extremist / Incitement ────────────────────────────────────────────────
    "aatankabad":       "आतंकवाद",
    "aatankwad":        "आतंकवाद",
    "aatankbad":        "आतंकवाद",
    "atankwadi":        "आतंकवादी",
    "aatankwadi":       "आतंकवादी",
    "narsanghar":       "नरसंहार",
    "narasanghar":      "नरसंहार",
    "narsangaar":       "नरसंहार",
    "jihad":            "जिहाद",
    "jihaad":           "जिहाद",
    "dharmahar":        "धर्मयुद्ध",
    "dharmayuddha":     "धर्मयुद्ध",
    "ugrabadi":         "उग्रवाद",
    "ugravad":          "उग्रवाद",
    "aatank":           "आतंक",
    "dahshat":          "दहशत",
    "danga":            "दंगा",
    "danga fasad":      "दंगा",
}



CONTEXT_SAFE = {
    "मर": [
        "मर्छु भने",        
        "मर्नु नपरोस्",     
        "अमर",              
        "नमर",              
        "मर्नु स्वाभाविक",  
    ],
    "मारोस्": [
        "नमारोस्",          
    ],
    "kill": [
        "skill",
        "kill it",
        "killing it",       
        "kill the vibe",    
        "kill time",
        "thriller kill",
        "overkill",
    ],
    "crazy": [
        "crazy good",
        "crazy talented",
        "crazy skills",
        "crazy beautiful",
        "crazy awesome",
    ],
    "hurt": [
        "hurt feelings",
        "doesn't hurt",
        "got hurt playing",
        "hurt my knee",
        "emotionally hurt",
    ],
    "die": [
        "die hard",
        "die laughing",
        "dye",             
        "i could die laughing",
        "die of cuteness",
    ],
    "bomb": [
        "bomb it",
        "bombed that presentation", 
        "bomb flavor",
        "logic bomb",      # computer science
        "f-bomb",
        "truth bomb",
    ],
    "fire": [
        "fire performance",
        "you're on fire",
        "fire song",
        "fire playlist",
        "campfire",
        "fire safety",
        "catch fire",      
    ],
    "cut": [
        "budget cut",
        "cut the rope",
        "haircut",
        "paper cut",
        "shortcut",
        "cut to the chase",
        "screenshot",
    ],
    "attack": [
        "attack the assignment",
        "panic attack",
        "heart attack",     
        "shark attack",     
        "cyber attack",     
    ],
    "shoot": [
        "shoot a photo",
        "shoot a film",
        "photo shoot",
        "shoot for the stars",
        "troubleshoot",
    ],
    "destroy": [
        "destroy the competition",   
        "destroyed the exam",        
        "self-destruct",
    ],
    "rot": [
        "rot in place",   
        "dry rot",
        "rot thirteen",   
    ],
    "poison": [
        "poison ivy",     
        "poison dart frog",
        "poison pill",    
    ],
    "stab": [
        "stab at",        
        "stab in the back",  
    ],
    "harass": [
        "anti-harassment",
        "prevent harassment",
    ],
    "cancer": [
        "cancer research",
        "fight cancer",
        "cancer survivor",
        "cancer awareness",
        "cancer treatment",
    ],
}



# WORD LIST METADATA

WORD_LIST_METADATA = {
    "version":      "2.1.0",
    "last_updated": "2083-03-15",       # Nepali BS date (≈ 2026-06-20 AD)
    "languages":    ["ne", "en", "ne-roman"],
    "categories": {
        "NORMAL":    {"description": "Safe, positive, everyday content"},
        "OFFENSIVE": {"description": "Rude, vulgar, insulting language"},
        "HATEFUL":   {"description": "Threats, violence, extremist content"},
    },
    "coverage": {
        "nepali_devanagari":  True,
        "english":            True,
        "romanized_nepali":   True,
        "nepali_phrases":     True,
        "english_phrases":    True,
        "subcategories":      True,
        "context_safelist":   True,
    },
    "features": {
        "weighted_scoring":   True,
        "phrase_detection":   True,
        "subcategories":      True,
        "romanized_map":      True,
        "context_safelist":   True,
    },
    "scoring_info": {
        "method":             "max(matched_word_scores)",
        "phrase_weight":      1.0,      # phrases always score at their full value
        "romanized_bonus":    0.05,     # small bonus for romanized evasion attempt
        "safelist_override":  True,     # context-safe words are skipped
    },
}


# PUBLIC API

__all__ = [
    "NORMAL_WORDS",
    "OFFENSIVE_WORDS",
    "HATEFUL_WORDS",
    "OFFENSIVE_SUBCATEGORIES",
    "HATEFUL_SUBCATEGORIES",
    "OFFENSIVE_PHRASES",
    "HATEFUL_PHRASES",
    "ROMANIZED_MAP",
    "CONTEXT_SAFE",
    "WORD_LIST_METADATA",
]

# Convenience: flat key sets for fast membership tests
OFFENSIVE_KEYS = set(OFFENSIVE_WORDS.keys())
HATEFUL_KEYS   = set(HATEFUL_WORDS.keys())


# STATISTICS  (auto-computed – no manual updates needed)

_WORD_COUNTS = {
    "normal":            len(NORMAL_WORDS),
    "offensive_words":   len(OFFENSIVE_WORDS),
    "hateful_words":     len(HATEFUL_WORDS),
    "offensive_phrases": len(OFFENSIVE_PHRASES),
    "hateful_phrases":   len(HATEFUL_PHRASES),
    "romanized_entries": len(ROMANIZED_MAP),
    "context_safe_entries": len(CONTEXT_SAFE),
    "total_items":       (
        len(NORMAL_WORDS) +
        len(OFFENSIVE_WORDS) +
        len(HATEFUL_WORDS) +
        len(OFFENSIVE_PHRASES) +
        len(HATEFUL_PHRASES)
    ),
}

if __name__ == "__main__":
    print("=== SabdaAI Word List Statistics (v2.0) ===")
    print(f"  Normal words        : {_WORD_COUNTS['normal']:,}")
    print(f"  Offensive words     : {_WORD_COUNTS['offensive_words']:,}")
    print(f"  Hateful words       : {_WORD_COUNTS['hateful_words']:,}")
    print(f"  Offensive phrases   : {_WORD_COUNTS['offensive_phrases']:,}")
    print(f"  Hateful phrases     : {_WORD_COUNTS['hateful_phrases']:,}")
    print(f"  Romanized map       : {_WORD_COUNTS['romanized_entries']:,} entries")
    print(f"  Context-safe entries: {_WORD_COUNTS['context_safe_entries']:,} entries")
    print(f"  ───────────────────────────────────────")
    print(f"  TOTAL items         : {_WORD_COUNTS['total_items']:,}")

    print()
    print("=== Offensive Subcategories ===")
    for cat, words in OFFENSIVE_SUBCATEGORIES.items():
        print(f"  {cat:<18}: {len(words)} words")

    print()
    print("=== Hateful Subcategories ===")
    for cat, words in HATEFUL_SUBCATEGORIES.items():
        print(f"  {cat:<18}: {len(words)} words")
